package answer.controller;

import answer.domain.Blank;
import answer.repository.BlankRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@Controller
@RequestMapping(path="/blank")
@CrossOrigin
public class BlankController {
    @Autowired // This means to get the bean called blankRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BlankRepository blankRepository;

    @PostMapping(path={"/add","/update"}, consumes = "application/json")
    public @ResponseBody String addOrUpdateBlank (@RequestBody Blank blank) {
        blankRepository.save(blank);
        return "Success";
    }

    @GetMapping(path="/getById/{id}")
    public @ResponseBody Optional<Blank> getBlankById(@PathVariable int id) {
        return blankRepository.findById(id);
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Blank> getAllBlanks() {
        return blankRepository.findAll();
    }

    @DeleteMapping("/{id}")
    public void removeById(@PathVariable int id) {
        blankRepository.deleteById(id);
    }

    @GetMapping(path="/getCount")
    public @ResponseBody long getCount(){
        return  blankRepository.count();
    }

    @GetMapping(path="/getPage{pageNumber}")
    public @ResponseBody Iterable<Blank> getPageData(@PathVariable int pageNumber){
        return blankRepository.findByQuestionStatusAndTestSubject("开放","语文",new PageRequest(pageNumber,7));
    }
}